### ISSUE TITLE
Few questions about the code

### ISSUE THREAD

**Issue by AOOOOOA** [HanjiangHu/Multi-LiDAR-Placement-for-3D-Detection#3]
Hi, Thanks for your work and time. I'm trying to read your code to figure out how to build a 3D occupancy grid using LiDAR data, but I just had a few questions. Could you please help with that?
 
 
![image](https://user-images.githubusercontent.com/38175747/195290022-954d6e0b-1b10-4597-b84b-76e74fd620c2.png)
1.The POG under the routes should be generated by CARLA or generated by ourselves? I didn't find the corresponding code if it needed to be generated by us. 
2. Is the class POM in /S_MIG/pom.py corresponding to the POG you described in your paper? 

Since the CARLA has changed API in the latest version so I cannot run the project directly.

Thanks!

**Comment by HanjiangHu** [comment]
Thanks for your interest in our work. The POG under the routes should be generated by CARLA because it is from the bounding box ground truth and it can also be generated by users if they use their own data with labels. The code for saving POG can be found in the function `create_datapoints` in `carla-kitti/scenario_runner/scenario_runner.py`. The class POM is used to calculate POG and surrogate metric and it is corresponding to the POG described in the paper. Sorry for the misunderstanding. 

I am sorry that the API has been changed in the latest version of CARLA, and we are also trying to update our repo. You are highly welcome to make pull requests if you can run it successfully with the latest CARLA.

Hope it is helpful to you.

**Comment by AOOOOOA** [comment]
> Thanks for your interest in our work. The POG under the routes should be generated by CARLA because it is from the bounding box ground truth and it can also be generated by users if they use their own data with labels. The code for saving POG can be found in the function `create_datapoints` in `carla-kitti/scenario_runner/scenario_runner.py`. The class POM is used to calculate POG and surrogate metric and it is corresponding to the POG described in the paper. Sorry for the misunderstanding.
> 
> I am sorry that the API has been changed in the latest version of CARLA, and we are also trying to update our repo. You are highly welcome to make pull requests if you can run it successfully with the latest CARLA.
> 
> Hope it is helpful to you.

Thanks!
